services:
  db:
    container_name: nest-kickstart-db
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - api
  filestore:
    restart: "always"
    container_name: minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    env_file:
      - .env
    volumes:
      - "filestore_data:/bitnami/minio/data"

networks:
  api:
    driver: bridge

volumes:
  db_data:
    driver: local
  cache:
    driver: local
  filestore_data:
    driver: local
